server:
  port: 8080
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: db_autenticacion_prg
    schema: public
    username: postgres
    password: qd7xcpag56
logging:
  level:
    org.springframework.r2dbc: "DEBUG"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
routes:
  paths:
    userLogin: "/api/v1/login"
    user: "/api/v1/usuarios"
    userById: "/api/v1/usuario/{id}"
    userByEmail: "/api/v1/usuario/email/{email}"